variant_id: lease_docusign_v1
doc_type: lease_agreement
identify:
  anchors_all_of:
    - "Lease Agreement"
    - "DocuSign Envelope ID"
extract:
  fields:
    agreement_type:
      strategy: literal
      value: "Lease Agreement"
    envelope_id:
      strategy: regex
      patterns:
        - "DocuSign Envelope ID[:\s]+([A-Z0-9-]+)"
    lessor_name:
      strategy: anchor_window
      anchor: "Lessor"
      window_lines_after: 1
    lessee_name:
      strategy: anchor_window
      anchor: "Lessee"
      window_lines_after: 1
    agreement_date:
      strategy: regex
      patterns:
        - "(Agreement Date|Dated)[:\s]+([0-9]{1,2}/[0-9]{1,2}/[0-9]{2,4})"
    term_months:
      strategy: regex
      patterns:
        - "(Term|Lease Term)[:\s]+([0-9]{1,3})\s*(months|mos|mths)?"
    total_amount_financed:
      strategy: regex
      patterns:
        - "(Total Amount Financed|Amount Financed)[:\s]*\$?([0-9,]+\.[0-9]{2})"
    monthly_payment:
      strategy: regex
      patterns:
        - "(Monthly Payment|Payment Amount|Rent)[:\s]*\$?([0-9,]+\.[0-9]{2})"
    serial_number:
      strategy: regex
      patterns:
        - "(Serial (Number|No\.)|S/N)[:\s]*([A-Za-z0-9-]+)"
    model_number:
      strategy: regex
      patterns:
        - "(Model (Number|No\.)|Model)[:\s]*([A-Za-z0-9-]+)"
